#!/usr/bin/env bash
# Render the homebrew formula for one release to stdout. The release workflow
# regenerates the whole file each release and commits it to
# prime-radiant-inc/homebrew-tap — no regex surgery on the previous formula.
#
#   scripts/make-formula.sh <version> <checksums.txt> > ledger.rb
#
# <version> may carry a leading v. checksums.txt is build-tarballs.sh output.
set -euo pipefail

version="${1:?usage: make-formula.sh <version> <checksums.txt>}"
version="${version#v}"
sums="${2:?usage: make-formula.sh <version> <checksums.txt>}"

sha() {
    awk -v f="ledger-$1.tar.gz" '$2 == f || $2 == "*"f {print $1}' "$sums"
}

for t in darwin-arm64 darwin-amd64 linux-arm64 linux-amd64; do
    [ -n "$(sha "$t")" ] || { echo "make-formula: no sha for $t in $sums" >&2; exit 1; }
done

dl="https://github.com/prime-radiant-inc/ledger/releases/download/v$version"

cat <<EOF
# Generated by scripts/make-formula.sh in prime-radiant-inc/ledger — edit there.
class Ledger < Formula
  desc "Durable, git-backed working-state for coding agents"
  homepage "https://github.com/prime-radiant-inc/ledger"
  version "$version"

  on_macos do
    if Hardware::CPU.arm?
      url "$dl/ledger-darwin-arm64.tar.gz"
      sha256 "$(sha darwin-arm64)"
    else
      url "$dl/ledger-darwin-amd64.tar.gz"
      sha256 "$(sha darwin-amd64)"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "$dl/ledger-linux-arm64.tar.gz"
      sha256 "$(sha linux-arm64)"
    else
      url "$dl/ledger-linux-amd64.tar.gz"
      sha256 "$(sha linux-amd64)"
    end
  end

  def install
    bin.install "ledger"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ledger version")
  end
end
EOF
